volumes:
  ml-data:
  ml-training:

services:
  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    ports:
      - "5000:5000"
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
    command: >
      mlflow server
      --backend-store-uri sqlite:///mlflow.db
      --default-artifact-root s3://${ARTIFACT_BUCKET}/
      --host 0.0.0.0
      --port 5000
      --cors-allowed-origins "*"
      --allowed-hosts "*"

  data-pipeline:
    build:
      context: .
      dockerfile: ./data_pipeline/Dockerfile
    container_name: data-pipeline
    environment:
      - ROLE=PRODUCER
    volumes:
      - ml-data:/data
      - ./training:/training
  training-pipeline:
    build:
      context: .
      dockerfile: ./training/Dockerfile
    gpus:
      - driver: nvidia
        count: all
        capabilities: [ gpu ]
    container_name: training-pipeline
    env_file:
      - .env
    environment:
      - ROLE=CONSUMER
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    volumes:
      - ml-data:/data
      - ./training:/training
    depends_on:
      data-pipeline:
        condition: service_completed_successfully
  analysis-pipeline:
    build:
      context: .
      dockerfile: ./analysis/Dockerfile
    container_name: analysis-pipeline
    environment:
      - ROLE=CONSUMER
    volumes:
      - ml-data:/data
      - ./training:/training
    depends_on:
      training-pipeline:
        condition: service_completed_successfully
  backtest-pipeline:
    build:
      context: .
      dockerfile: ./backtest/Dockerfile
    container_name: backtest-pipeline
    environment:
      - ROLE=CONSUMER
    volumes:
      - ml-data:/data
      - ./training:/training
    depends_on:
      analysis-pipeline:
        condition: service_completed_successfully