volumes:
  ml-data:
  ml-training:

services:
  api:
    image: 742600926264.dkr.ecr.eu-west-2.amazonaws.com/ml-signal-service/pipeline:api
    env_file: .env
    profiles: [ "serve" ]
    ports:
      - "8000:8000"
  data-pipeline:
    build:
      context: .
      dockerfile: ./data_pipeline/Dockerfile
    container_name: data-pipeline
    environment:
      - ROLE=PRODUCER
    profiles: [ "train" ]
    volumes:
      - ml-data:/data
      - ./training:/training
  training-pipeline:
    build:
      context: .
      dockerfile: ./training/Dockerfile
    gpus:
      - driver: nvidia
        count: all
        capabilities: [ gpu ]
    container_name: training-pipeline
    env_file:
      - .env
    profiles: [ "train" ]
    environment:
      - ROLE=CONSUMER
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - MLFLOW_TRACKING_URI=${MLFLOW_TRACKING_URI}
    volumes:
      - ml-data:/data
      - ./training:/training
    depends_on:
      data-pipeline:
        condition: service_completed_successfully
  analysis-pipeline:
    build:
      context: .
      dockerfile: ./analysis/Dockerfile
    container_name: analysis-pipeline
    environment:
      - ROLE=CONSUMER
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - MLFLOW_TRACKING_URI=${MLFLOW_TRACKING_URI}
    profiles: [ "train" ]
    volumes:
      - ml-data:/data
      - ./training:/training
    depends_on:
      training-pipeline:
        condition: service_completed_successfully
  backtest-pipeline:
    build:
      context: .
      dockerfile: ./backtest/Dockerfile
    container_name: backtest-pipeline
    environment:
      - ROLE=CONSUMER
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - MLFLOW_TRACKING_URI=${MLFLOW_TRACKING_URI}
    profiles: [ "train" ]
    volumes:
      - ml-data:/data
      - ./training:/training
    depends_on:
      analysis-pipeline:
        condition: service_completed_successfully